// Known MetroVan walk-in clinics on Cortico
// Source: https://cortico.health/specialties/walk-in/

export interface ClinicConfig {
  name: string
  subdomain: string
  city: string
  address: string
  latitude: number
  longitude: number
  locations?: { name: string; slug: string }[] // multi-location clinics
  knownProviderIds?: number[] // if already discovered
  phone?: string
  website?: string
}

export const CLINICS: ClinicConfig[] = [
  // === NORTH VANCOUVER ===
  {
    name: 'Carefiniti Lynn Medical Clinic',
    subdomain: 'carefiniti',
    city: 'North Vancouver',
    address: '3167 Mountain Hwy, North Vancouver, BC',
    latitude: 49.3297,
    longitude: -123.0287,
    locations: [{ name: 'Lynn', slug: '0' }],
    knownProviderIds: [127],
  },
  {
    name: 'Carefiniti Marine Medical Clinic',
    subdomain: 'carefiniti',
    city: 'North Vancouver',
    address: '1277 Marine Dr, North Vancouver, BC',
    latitude: 49.3216,
    longitude: -123.0762,
    locations: [{ name: 'Marine', slug: 'm' }],
    knownProviderIds: [127],
  },
  {
    name: 'Carefiniti West Lonsdale Medical Clinic',
    subdomain: 'carefiniti',
    city: 'North Vancouver',
    address: 'Unit 150-145 17th West Street, North Vancouver, BC',
    latitude: 49.3258,
    longitude: -123.1074,
    locations: [{ name: 'West Lonsdale', slug: 'l' }],
    knownProviderIds: [127],
  },
  {
    name: 'Five Points Medical Clinic',
    subdomain: 'fivepoints',
    city: 'North Vancouver',
    address: '#102 - 711 14th St W, North Vancouver, BC',
    latitude: 49.3243,
    longitude: -123.1042,
  },
  {
    name: 'iHealthMD Medical Centre',
    subdomain: 'ihealthmd',
    city: 'North Vancouver',
    address: '972 Marine Dr, North Vancouver, BC',
    latitude: 49.3224,
    longitude: -123.0800,
  },
  {
    name: 'Kian Care Clinic',
    subdomain: 'kiancare',
    city: 'North Vancouver',
    address: '3711 Delbrook Ave, North Vancouver, BC',
    latitude: 49.3460,
    longitude: -123.0910,
  },
  {
    name: 'Legacies Health Centre',
    subdomain: 'legacies',
    city: 'North Vancouver',
    address: '1394 Main St, North Vancouver, BC',
    latitude: 49.3147,
    longitude: -123.0685,
  },
  {
    name: 'Lynn Valley Medical Clinic',
    subdomain: 'lynnvalley',
    city: 'North Vancouver',
    address: 'Suite #102, 1200 Lynn Valley Road, North Vancouver, BC',
    latitude: 49.3370,
    longitude: -123.0280,
  },
  {
    name: 'Lonsdale Medical Clinics',
    subdomain: 'lonsdale',
    city: 'North Vancouver',
    address: '108-1940 Lonsdale Ave, North Vancouver, BC',
    latitude: 49.3300,
    longitude: -123.0750,
  },

  // === WEST VANCOUVER ===
  {
    name: 'Park Medical Clinic',
    subdomain: 'parkmedicalclinic',
    city: 'West Vancouver',
    address: 'Unit 204-1571 Bellevue Ave, West Vancouver, BC',
    latitude: 49.3260,
    longitude: -123.1380,
  },
  {
    name: 'Healthwise Caulfeild Medical Clinic',
    subdomain: 'healthwise',
    city: 'West Vancouver',
    address: '5476 Marine Dr, West Vancouver, BC',
    latitude: 49.3410,
    longitude: -123.2490,
    locations: [{ name: 'Caulfeild', slug: 'caulfeild-medical-clinic' }],
  },
  {
    name: 'Healthwise Coal Harbour Health Centre',
    subdomain: 'healthwise',
    city: 'Vancouver',
    address: '1277 Melville St, Vancouver, BC',
    latitude: 49.2890,
    longitude: -123.1230,
    locations: [{ name: 'Coal Harbour', slug: 'coal-harbour-health-centre' }],
  },
  {
    name: 'Healthwise Garden Medical Clinic',
    subdomain: 'healthwise',
    city: 'Vancouver',
    address: '4088 Cambie St, Vancouver, BC',
    latitude: 49.2490,
    longitude: -123.1150,
    locations: [{ name: 'Garden', slug: 'garden-medical-clinic' }],
  },
  {
    name: 'Healthwise Mount Seymour Medical Clinic',
    subdomain: 'healthwise',
    city: 'North Vancouver',
    address: '1020 Deep Cove Rd, North Vancouver, BC',
    latitude: 49.3360,
    longitude: -123.0040,
    locations: [{ name: 'Mount Seymour', slug: 'mount-seymour-medical-clinic' }],
  },
  {
    name: 'Healthwise Orca Medical Clinic',
    subdomain: 'healthwise',
    city: 'Vancouver',
    address: '205-2083 Alma St, Vancouver, BC',
    latitude: 49.2660,
    longitude: -123.1680,
    locations: [{ name: 'Orca', slug: 'orca-medical-clinic' }],
  },

  // === VANCOUVER ===
  {
    name: 'Downtown Vancouver Medical Clinic',
    subdomain: 'downtownvancouverclinic',
    city: 'Vancouver',
    address: '1102 W Pender St, Vancouver, BC',
    latitude: 49.2860,
    longitude: -123.1210,
  },
  {
    name: 'Granville Medical Clinic',
    subdomain: 'granvillemedical',
    city: 'Vancouver',
    address: '2578 Granville St, Vancouver, BC',
    latitude: 49.2630,
    longitude: -123.1390,
  },
  {
    name: 'MD 4 ME',
    subdomain: 'md4me',
    city: 'Vancouver',
    address: 'Unit 103 - 2025 West Broadway, Vancouver, BC',
    latitude: 49.2634,
    longitude: -123.1520,
  },
  {
    name: 'Alberni Medical Clinic',
    subdomain: 'albernimedicalclinic',
    city: 'Vancouver',
    address: '1318 Alberni St, Vancouver, BC',
    latitude: 49.2850,
    longitude: -123.1280,
  },
  {
    name: 'Commercial Drive Medical Clinic',
    subdomain: 'commercialdrivemedical',
    city: 'Vancouver',
    address: '1515 Commercial Dr, Vancouver, BC',
    latitude: 49.2720,
    longitude: -123.0700,
  },
  {
    name: 'ConnectMD',
    subdomain: 'connectmd',
    city: 'Vancouver',
    address: '4209 Fraser Street, Vancouver, BC',
    latitude: 49.2490,
    longitude: -123.0900,
  },
  {
    name: 'Fraser Care Clinic',
    subdomain: 'frasercare',
    city: 'Vancouver',
    address: '6460 Fraser St, Vancouver, BC',
    latitude: 49.2280,
    longitude: -123.0890,
  },
  {
    name: 'Collingwood Medical Clinic',
    subdomain: 'collingwood',
    city: 'Vancouver',
    address: 'Suite 350 - 3150 54th Ave E, Vancouver, BC',
    latitude: 49.2250,
    longitude: -123.0390,
  },
  {
    name: 'REACH Community Health Centre',
    subdomain: 'reachcentre',
    city: 'Vancouver',
    address: '1145 Commercial Dr, Vancouver, BC',
    latitude: 49.2750,
    longitude: -123.0700,
  },
  {
    name: 'WELL Health Grandview',
    subdomain: 'wellhealthgrandview',
    city: 'Vancouver',
    address: '3185 Grandview Hwy, Vancouver, BC',
    latitude: 49.2550,
    longitude: -123.0450,
  },
  {
    name: 'Vy Care Kingsway',
    subdomain: 'vycare',
    city: 'Vancouver',
    address: '3587 Kingsway, Vancouver, BC',
    latitude: 49.2400,
    longitude: -123.0600,
    locations: [{ name: 'Kingsway', slug: 'vycare-kingsway' }],
  },
  {
    name: 'Vy Care Broadway',
    subdomain: 'vycare',
    city: 'Vancouver',
    address: '730-943 W Broadway, Vancouver, BC',
    latitude: 49.2634,
    longitude: -123.1240,
    locations: [{ name: 'Broadway', slug: 'vycare-broadway' }],
  },

  // === BURNABY ===
  {
    name: 'Welcome Medical Clinic',
    subdomain: 'welcomemedical',
    city: 'Burnaby',
    address: '4885 Kingsway #218, Burnaby, BC',
    latitude: 49.2270,
    longitude: -123.0050,
    knownProviderIds: [82, 242],
  },
  {
    name: 'Maywood Medical',
    subdomain: 'maywoodmedical',
    city: 'Burnaby',
    address: '4980 Kingsway, Unit 110, Burnaby, BC',
    latitude: 49.2278,
    longitude: -123.0030,
  },
  {
    name: 'Station Square Medical Clinic',
    subdomain: 'stationsquare',
    city: 'Burnaby',
    address: '#150 - 6200 McKay Ave, Burnaby, BC',
    latitude: 49.2260,
    longitude: -122.9840,
  },
  {
    name: 'WELL Health Kensington (KMC)',
    subdomain: 'kmc',
    city: 'Burnaby',
    address: '6548 Hastings St, Burnaby, BC',
    latitude: 49.2810,
    longitude: -122.9580,
  },
  {
    name: 'Elicare Lougheed Medical Clinic',
    subdomain: 'elicarelougheed',
    city: 'Burnaby',
    address: '9618 Cameron St, Burnaby, BC',
    latitude: 49.2490,
    longitude: -122.8950,
  },
  {
    name: 'IME Burnaby',
    subdomain: 'imeburnaby',
    city: 'Burnaby',
    address: '104-3965 Kingsway, Burnaby, BC',
    latitude: 49.2330,
    longitude: -123.0110,
  },
  {
    name: 'TLC Medical',
    subdomain: 'tlc',
    city: 'Burnaby',
    address: '4300 Kingsway, Burnaby, BC',
    latitude: 49.2310,
    longitude: -123.0090,
  },
  {
    name: 'VyCare Brentwood',
    subdomain: 'vycare',
    city: 'Burnaby',
    address: '216-4279 Dawson St, Burnaby, BC',
    latitude: 49.2680,
    longitude: -123.0080,
    locations: [{ name: 'Brentwood', slug: 'vycare-brentwood' }],
  },

  // === SURREY ===
  {
    name: 'ACE Medical Clinic',
    subdomain: 'acemedical',
    city: 'Surrey',
    address: '#103 12030 80 Ave, Surrey, BC',
    latitude: 49.1540,
    longitude: -122.8740,
  },
  {
    name: 'Focus Medical Clinic',
    subdomain: 'focusmed',
    city: 'Surrey',
    address: '15135 101 Ave #200, Surrey, BC',
    latitude: 49.1890,
    longitude: -122.7750,
  },
  {
    name: 'Generations Med Clinic',
    subdomain: 'generationsmedclinic',
    city: 'Surrey',
    address: '102B 6844 King George Blvd, Surrey, BC',
    latitude: 49.1230,
    longitude: -122.8470,
  },
  {
    name: 'Sullivan Medical Clinic',
    subdomain: 'sullivanmedical',
    city: 'Surrey',
    address: 'Suite 108 - 15325 56th Ave, Surrey, BC',
    latitude: 49.1080,
    longitude: -122.7730,
  },
  {
    name: 'Bear Creek Medical Clinic',
    subdomain: 'bearcreek',
    city: 'Surrey',
    address: '9093 King George Blvd #105, Surrey, BC',
    latitude: 49.1670,
    longitude: -122.8480,
  },
  {
    name: 'Pulse Medical',
    subdomain: 'pulsemedical',
    city: 'Surrey',
    address: '19567 64 Ave, Unit 1&2, Surrey, BC',
    latitude: 49.1170,
    longitude: -122.7120,
  },
  {
    name: 'Pure Cure Medical Clinic',
    subdomain: 'purecure',
    city: 'Surrey',
    address: 'Unit 100-8820 120 St, Surrey, BC',
    latitude: 49.1610,
    longitude: -122.8730,
  },
  {
    name: 'Viva Care Telehealth',
    subdomain: 'vivacare',
    city: 'Surrey',
    address: '#1026-10153 King George Blvd, Surrey, BC',
    latitude: 49.1870,
    longitude: -122.8490,
  },
  {
    name: 'WELL Health South Surrey',
    subdomain: 'southsurrey',
    city: 'Surrey',
    address: '#101 15850 26th Ave, Surrey, BC',
    latitude: 49.0450,
    longitude: -122.7670,
  },

  // === RICHMOND ===
  {
    name: 'Garden City Medical Clinic',
    subdomain: 'gardencitymed',
    city: 'Richmond',
    address: '190-9040 Blundell Rd, Richmond, BC',
    latitude: 49.1700,
    longitude: -123.1300,
  },
  {
    name: 'Thrive Medical Clinic',
    subdomain: 'thrivemedical',
    city: 'Richmond',
    address: '#8060 11688 Steveston Hwy, Richmond, BC',
    latitude: 49.1250,
    longitude: -123.0790,
  },
  {
    name: 'Elicare Richmond Medical Clinic',
    subdomain: 'elicarerichmond',
    city: 'Richmond',
    address: '140-5611 Cooney Rd, Richmond, BC',
    latitude: 49.1680,
    longitude: -123.1370,
  },
  {
    name: 'Well Health Medical Centre Richmond',
    subdomain: 'wellhealth',
    city: 'Richmond',
    address: '100-12420 No. 1 Road, Richmond, BC',
    latitude: 49.1300,
    longitude: -123.1430,
  },
  {
    name: 'Megafu Medical Clinic',
    subdomain: 'megafuclinic',
    city: 'Richmond',
    address: '4000 No. 3 Rd, Richmond, BC',
    latitude: 49.1660,
    longitude: -123.1330,
  },

  // === NEW WESTMINSTER ===
  {
    name: 'Belmont Medical Clinic',
    subdomain: 'belmont',
    city: 'New Westminster',
    address: '609 Belmont Street, New Westminster, BC',
    latitude: 49.2100,
    longitude: -122.9080,
  },
  {
    name: 'ForeMed',
    subdomain: 'foremed',
    city: 'New Westminster',
    address: '420 Columbia Street, New Westminster, BC',
    latitude: 49.2040,
    longitude: -122.9100,
  },
  {
    name: 'Pacific Heights Health Centre',
    subdomain: 'pacificheights',
    city: 'New Westminster',
    address: '101-42 Sixth Street, New Westminster, BC',
    latitude: 49.2040,
    longitude: -122.9150,
  },
  {
    name: 'Royal Columbia Medical Clinic',
    subdomain: 'royalcolumbia',
    city: 'New Westminster',
    address: '330 E Columbia St, New Westminster, BC',
    latitude: 49.2110,
    longitude: -122.9070,
  },

  // === COQUITLAM / PORT COQUITLAM / PORT MOODY ===
  {
    name: 'Foothills Medical Clinic',
    subdomain: 'foothills',
    city: 'Coquitlam',
    address: '203-3387 David Ave, Coquitlam, BC',
    latitude: 49.2800,
    longitude: -122.7930,
  },
  {
    name: 'Rocky Point Medical',
    subdomain: 'rockypoint',
    city: 'Port Moody',
    address: '2602 St Johns St, Port Moody, BC',
    latitude: 49.2840,
    longitude: -122.8560,
  },

  // === MAPLE RIDGE ===
  {
    name: 'Pure Care Maple Ridge',
    subdomain: 'purecaremaple',
    city: 'Maple Ridge',
    address: '105-22470 Dewdney Trunk Rd, Maple Ridge, BC',
    latitude: 49.2200,
    longitude: -122.5970,
  },
  {
    name: 'Trust Care Clinic',
    subdomain: 'trustcare',
    city: 'Maple Ridge',
    address: '22470 Dewdney Trunk Rd #100, Maple Ridge, BC',
    latitude: 49.2200,
    longitude: -122.5970,
  },

  // === DELTA ===
  {
    name: 'Primacy Medical Clinic',
    subdomain: 'drsheikprimacy',
    city: 'Delta',
    address: '8195 120 Street, North Delta, BC',
    latitude: 49.1570,
    longitude: -122.8920,
  },
]

// Get unique subdomains (some clinics share subdomains with different locations)
export function getUniqueSubdomains(): string[] {
  return [...new Set(CLINICS.map(c => c.subdomain))]
}
